version: '3'

services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    # Add volumes for more production like setup
  node:
    build: ./
    image: webapp:dev
    ports:
      - 8080:8080
    expose:
      - 8080